### ISSUE TITLE
Roadmap v0.1

### ISSUE THREAD

**Issue by Yogu** [Yogu/site-manager#1]
### Backups
- [x] save and restore repo revision
- [ ] show metadata (size, contents?)
- [x] support mysql (also for migrations)
### UI
- [ ] cache contents and trigger reloads on socket events (e.g. backups)
- [ ] enhance sidebar navigation
- [ ] enhance latest task display
- [ ] faster task loading by lazy-loading the log
- [ ] send log of shell tasks during execution
- [ ] hide load tasks
### Other features
- [x] Execute bash script after checkout
- [x] Send mails on success/error
